### ISSUE TITLE
Line 183 train 3dnet cat 

### ISSUE THREAD

**Issue by zig-zagreus** [J-Cuadrado/OF_EV_SNN#3]
hi, for line 183 for the train 3dNet cat, the raise is being read as an error, saying that "No exception to reraise"

**Comment by J-Cuadrado** [comment]
Hello, that exception is raised when gradients disappear in training, usually due to not enough activation at a certain point within the network. We have found that a way to counteract this problem is by increasing the MultiplyFactor value, since it is equivalent to reducing the firing threshold and therefore encourages activity within the network. I hope this is of help to you, do not hesitate to contact us for further queries (:

**Comment by zig-zagreus** [comment]
Brilliant thank you so  much for letting me know!
